config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
      :confirmations => 'users/confirmations',
      registrations: "users/registrations",
  }

  devise_scope :user do
    patch "users/confirm" => "users/confirmations#confirm"
  end

  resources :pages

  resources :expenses
  resources :profiles , only:[:index,:show] do
    resources :relationships, only: [:create, :destroy]
  end

  get "/"=>'tops#index'
  get "/about"=>'tops#about'
  get "profile/search"=>"profiles#search"


  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @mates = current_user.followings_list
    @users = User.all
  end

  def show
    @user = User.find_by(userid: params[:id])
    if @user == nil
      redirect_to profiles_path, notice: "そのユーザーidは存在しませんでした"
    end
  end

  def search
    redirect_to profile_path(params[:name])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/index.html.erb
<div class="item-list">

  <p>ユーザーを検索</p>
  <nav class="navbar">
      <%= form_with url: profile_search_path,:method => 'get',class: "container-fluid" do |f| %>
      <div class="input-group">
        <span class="input-group-text" id="basic-addon1">@</span>
        <%= f.text_field :name, class: "form-control",placeholder: "UserName",aria: {label:"Username",describedby: "basic-addon1"}%>
        <!--<input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">-->
      </div>
        <% end %>
  </nav>

  <div class="item-list-header">
    <p class="bold">フォローリスト</p>
  </div>

  <div class="item-list-content">
    <ul>
      <% @mates.each do |user| %>
        <div class="each-item">
          <li>
            <div class="each-item-content">

              <div class="item-content-left">
                <!--ユーザー画像-->
              </div>

              <div class="item-content-right">
                <p><%= link_to user.username, profile_path(user.userid) %></p>
              </div>

            </div>
          </li>
        </div>
      <% end %>
    </ul>
  </div>

  <div class="item-list-header">
    <p class="bold">おすすめユーザー</p>
  </div>

  <div class="item-list-content">
    <ul>
      <% @users.shuffle.first(5).each do |user| %>
        <% unless current_user.id == user.id %>
          <% unless current_user.following?(user) %>
            <div class="each-item">

              <li>
                <div class="each-item-content">
                  <div class="item-content-left">
                    <!--ユーザー画像-->
                  </div>
                  <div class="item-content-right">
                    <p><%= link_to user.username, profile_path(user.userid) %></p>
                    <% if user.follow_request?(current_user, user) %>
                      <p><i class="fas fa-star"></i></p>
                    <% end %>
                  </div>
                </div>
              </li>

            </div>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="form-wrap">
  <div class="form-group">
    <div class="schedule-item">
      <div class="schedule-item-body text-left">
        <h1><%= @user.username %></h1><p>@<%= @user.userid %></p>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="schedule-item">
      <div class="schedule-item-body text-left">
        <p>お気に入りの台 : <%= @user.favorite %></p>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="schedule-item">
      <div class="schedule-item-body text-left">
        <p>自己紹介 : <%= @user.about %></p>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="schedule-item">
      <div class="schedule-item-body text-left">
        <p>フォロー中 : <%= @user.followings_list.count %></p>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="schedule-item">
      <div class="schedule-item-body text-left">
        <p>フォロワー : <%= @user.followers_list.count %></p>
      </div>
    </div>
  </div>

  <% if @user.follow_request?(current_user, @user) %>
    <div class="form-group">
      <div class="schedule-item">
        <div class="schedule-item-header text-left">
          <p class="bold">フォローされています</p>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user.matchers?(@user) %>
    <div class="form-group">
      <div class="schedule-item">
        <div class="schedule-item-header text-left">
          <p class="bold">相互フォローです</p>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user.id == @user.id %>

  <% else %>
    <% unless current_user.following?(@user) %>
      <div class="actions">
        <%= link_to 'フォローする', profile_relationships_path(@user.userid), method: :post, class:"sign-up-btn" %>
      </div>
    <% else %>
      <div class="actions">
        <%= link_to 'フォローを解除する',  profile_relationship_path(@user.userid), method: :delete, class:"sign-up-btn" %>
      </div>
    <% end %>
  <% end %>

  <% if current_user.id == @user.id %>
    <div class="actions">
      <%= link_to 'プロフィールを編集する', edit_user_registration_path, class:"sign-up-btn" %>
    </div>
  <% end %>
</div>