config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
      :confirmations => 'users/confirmations',
      registrations: "users/registrations",
  }

  devise_scope :user do
    patch "users/confirm" => "users/confirmations#confirm"
  end

  resources :pages

  resources :expenses
  resources :profiles , only:[:index,:show] do
    resources :relationships, only: [:create, :destroy]
  end

  get "/"=>'tops#index'
  get "/about"=>'tops#about'
  get "profile/search"=>"profiles#search"


  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>CherryPie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <% if user_signed_in? %>
            <%= link_to 'CherryPie', pages_path, class: "navbar-brand"%>
          <% else %>
            <%= link_to 'CherryPie', "/", class: "navbar-brand"%>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <% if user_signed_in? %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= current_user.username %>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li> <%= link_to "マイページ", profile_path(id: current_user.userid), class: "dropdown-item" %></li>
                    <li> <%= link_to 'サインアウト', destroy_user_session_path, class: "dropdown-item", method: :delete %></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <%= link_to '収支管理', expenses_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'フレンド', profiles_path, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'サインアップ', new_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'サインイン', new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
            <% if user_signed_in? %>
              <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main class="flex-shrink-0">
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="notice"><%= alert %></p>
        <%= yield %>
      </div>
    </main>

    <footer class="footer mt-auto py-3 bg-dark">
      <div class="container  text-center">
        <span class="text-muted">©2021 yurisi All rights reserved.</span>
      </div>
    </footer>
  </body>
</html>